# Generated by Django 2.2.7 on 2019-11-12 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20191112_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_quality',
        ),
        migrations.AlterField(
            model_name='game',
            name='game_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team', to='manager.League'),
        ),
    ]
