# Generated by Django 2.2.7 on 2019-11-12 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20191112_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_date',
            new_name='date',
        ),
    ]
